CREATE DATABASE IF NOT EXISTS board DEFAULT CHARACTER SET utf8mb4;

USE board;

CREATE TABLE IF NOT EXISTS posts (
  id      INT AUTO_INCREMENT PRIMARY KEY,
  title   VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  regdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4;

